phases:
    build:
        commands:
            - export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --output text --query 'Account')
            - export IMAGE_TAG=test
            - export APP_VERSION=1.0.0
            - chmod +x ./ci/docker-deploy.sh
            - ./ci/docker-deploy.sh --account-id "${AWS_ACCOUNT_ID}" --region "${AWS_DEFAULT_REGION}" --repo "${REPO_NAME}" --tag "${IMAGE_TAG}" --version "${APP_VERSION}" --branch master --env dev
